# File managed by pluginsync
sudo: true
language: go
go:
- 1.7.x
- 1.8.x
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/cuongquay
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  - GLIDE_HOME="${HOME}/.glide"
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE: build
matrix:
  exclude:
  - go: 1.7.x
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
- chmod +x scripts/*
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - release/snap-plugin-collector-csvreader_linux_x86_64
  skip_cleanup: true
  on:
    repo: cuongquay/snap-plugin-collector-csvreader
    branch: master
    tags: false
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.8(|\.[0-9]+)$
